In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
%load_ext nb_black

<IPython.core.display.Javascript object>

In [3]:
tf.__version__


'2.8.0'

<IPython.core.display.Javascript object>

In [4]:
scalar = tf.constant(7)

<IPython.core.display.Javascript object>

In [5]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

<IPython.core.display.Javascript object>

In [6]:
np.ndim(scalar)

0

<IPython.core.display.Javascript object>

In [7]:
scalar.ndim

0

<IPython.core.display.Javascript object>

In [8]:
vector = tf.constant([10, 10])

<IPython.core.display.Javascript object>

In [9]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

<IPython.core.display.Javascript object>

In [10]:
vector.ndim

1

<IPython.core.display.Javascript object>

In [11]:
matrix = tf.constant([[10.0, 9], [3, 4]])

<IPython.core.display.Javascript object>

In [12]:
matrix.ndim

2

<IPython.core.display.Javascript object>

In [13]:
matrix

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10.,  9.],
       [ 3.,  4.]], dtype=float32)>

<IPython.core.display.Javascript object>

In [14]:
Tensors = tf.constant(
    [[[1, 2, 3], [4, 6, 4]], [[1, 6, 8], [1, 8, 0]], [[1, 5, 8], [1, 10, 2]]]
)

<IPython.core.display.Javascript object>

In [15]:
Tensors

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  6,  4]],

       [[ 1,  6,  8],
        [ 1,  8,  0]],

       [[ 1,  5,  8],
        [ 1, 10,  2]]])>

<IPython.core.display.Javascript object>

In [16]:
Tensors.ndim

3

<IPython.core.display.Javascript object>

In [17]:
c_tensor = tf.Variable([10, 7])

<IPython.core.display.Javascript object>

In [18]:
c_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>

<IPython.core.display.Javascript object>

In [19]:
# c_tensor[0] = 10

<IPython.core.display.Javascript object>

In [20]:
c_tensor.assign([7, 8])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 8])>

<IPython.core.display.Javascript object>

In [21]:
c_tensor[0].assign(9)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([9, 8])>

<IPython.core.display.Javascript object>

In [22]:
# random_tensor = tf.random.Generator.from_seed(42)

random_tensor = tf.random.uniform(
    shape=[3, 3, 3], dtype=tf.dtypes.int32, minval=1, maxval=10, seed=5
)
random_tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[5, 3, 7],
        [9, 6, 2],
        [8, 6, 6]],

       [[4, 3, 7],
        [5, 4, 8],
        [1, 9, 5]],

       [[9, 2, 5],
        [8, 8, 6],
        [7, 5, 6]]])>

<IPython.core.display.Javascript object>

In [23]:
random_tensor_normal = tf.random.uniform(
    shape=[3, 3, 3], dtype=tf.dtypes.float32, minval=1, maxval=10, seed=5
)
random_tensor_normal

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[4.4948015, 6.9731455, 2.7271967],
        [7.354474 , 9.668651 , 3.936549 ],
        [7.386671 , 6.8320546, 2.201767 ]],

       [[6.1613417, 5.021452 , 5.0302186],
        [5.844374 , 7.490732 , 7.6501584],
        [3.7726038, 2.0718932, 2.5272593]],

       [[1.8391902, 6.965706 , 8.674449 ],
        [7.238255 , 9.638839 , 5.433477 ],
        [8.501412 , 6.6321564, 3.9320192]]], dtype=float32)>

<IPython.core.display.Javascript object>